version: "2"
exclude_patterns:
  - "**/node_modules/"
  - "**/__tests__/"
  - "**/__test__/"
  - "**/*.d.ts"
plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      ignore_warnings: true
      extensions:
        - .es6
        - .js
        - .jsx
        - .mjs

