language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "8"
notifications:
  email:
    recipients:
      - getinor@icloud.com
    on_success: change
    on_failure: always
install:
  - npm install

script:
  - npm run build
  - git config --global user.name "Travis CI"
  - git config --global user.email "getinor@icloud.com"
  - export GIT_PUBLISH_URL=https://${GH_TOKEN}@github.com/wwayne/react-tooltip.git
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run gh-pages -- --repo ${GIT_PUBLISH_URL}; fi

after_success:
  - npm run semantic-release

branches:
  except:
- "/^v\\d+\\.\\d+\\.\\d+$/"